apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "prom-stack-chart.fullname" . }}-promtail
  labels:
    {{- include "prom-stack-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "prom-stack-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: promtail
  template:
    metadata:
      labels:
        {{- include "prom-stack-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: promtail
    spec:
      serviceAccountName: {{ include "prom-stack-chart.serviceAccountName" . }}
      containers:
        - name: promtail
          {{- $promtail := .Values.promtail | default dict }}
          {{- $image := $promtail.image | default dict }}
          image: "{{ $image.repository | default "grafana/promtail" }}:{{ $image.tag | default "2.8.2" }}"
          imagePullPolicy: {{ $image.pullPolicy | default "IfNotPresent" }}
          args:
            - "-config.file=/etc/promtail/promtail.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: run
              mountPath: /run/promtail
            - name: docker
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: pods
              mountPath: /var/log/pods
              readOnly: true
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 9080
              name: http-metrics
      volumes:
        - name: config
          configMap:
            name: {{ include "prom-stack-chart.fullname" . }}-promtail
        - name: run
          hostPath:
            path: /run/promtail
        - name: docker
          hostPath:
            path: /var/lib/docker/containers
        - name: pods
          hostPath:
            path: /var/log/pods
