apiVersion: v1
kind: Service
metadata:
  name: {{ include "prom-stack-chart.fullname" . }}-node-exporter
  labels:
    {{- include "prom-stack-chart.labels" . | nindent 4 }}
    component: node-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9100
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "prom-stack-chart.selectorLabels" . | nindent 4 }}
    component: node-exporter
