apiVersion: v1
kind: Service
metadata:
  name: {{ include "prom-stack-chart.fullname" . }}-pushgateway
  labels:
    {{- include "prom-stack-chart.labels" . | nindent 4 }}
    component: pushgateway
spec:
  type: {{ .Values.pushgateway.service.type }}
  ports:
    - port: {{ .Values.pushgateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "prom-stack-chart.selectorLabels" . | nindent 4 }}
    component: pushgateway
