apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
type: Opaque
stringData:
  # Grafana admin credentials
  admin-user: {{ .Values.grafana.adminUser | default "admin" | quote }}
  admin-password: {{ .Values.grafana.adminPassword | default "admin123" | quote }}
  # Additional secret data
  grafana-secret-key: {{ .Values.grafana.secretKey | default "default-grafana-secret" | quote }}
