{{- if .Values.grafana.datasources.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prom-stack-chart.fullname" . }}-grafana-datasources
  labels:
    {{- include "prom-stack-chart.labels" . | nindent 4 }}
    component: grafana
    grafana_datasource: "1"
type: Opaque
stringData:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://{{ include "prom-stack-chart.fullname" . }}-prometheus:9090
        access: proxy
        isDefault: true
{{- end }}
