apiVersion: v1
kind: Secret
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
type: Opaque
data:
  # Add your base64-encoded secret data here
  # Example: auth-token: <base64-encoded-value>
stringData:
  # Or use stringData for plain text that will be auto-encoded
  loki-config-secret: {{ .Values.loki.secretData | default "default-secret-value" | quote }}
