apiVersion: v1
kind: Secret
metadata:
  name: loki-promtail
  namespace: monitoring
  labels:
    app: promtail
type: Opaque
stringData:
  # Promtail authentication token or credentials
  promtail-token: {{ .Values.promtail.secretData | default "default-promtail-token" | quote }}
