apiVersion: v1
kind: Service
metadata:
  name: loki-memberlist
  namespace: monitoring
  labels:
    app: loki
spec:
  clusterIP: None
  ports:
    - port: 7946
      targetPort: memberlist
      protocol: TCP
      name: memberlist
  selector:
    app: loki
