apiVersion: v1
kind: Service
metadata:
  name: loki-headless
  namespace: monitoring
  labels:
    app: loki
spec:
  clusterIP: None
  ports:
    - port: 3100
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    app: loki
