apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "prom-stack-chart.fullname" . }}-loki
  labels:
    {{- include "prom-stack-chart.labels" . | nindent 4 }}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      {{- include "prom-stack-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: loki
  serviceName: {{ include "prom-stack-chart.fullname" . }}-loki-headless
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "prom-stack-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: loki
    spec:
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: loki
          image: "{{ .Values.loki.image.repository }}:{{ .Values.loki.image.tag }}"
          imagePullPolicy: {{ .Values.loki.image.pullPolicy }}
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
            - name: memberlist
              containerPort: 7946
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          livenessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
            timeoutSeconds: 1
      volumes:
        - name: config
          configMap:
            name: {{ include "prom-stack-chart.fullname" . }}-loki
        - name: storage
          emptyDir: {}
